name: Deploying Wordpress with Prometheus monitoring and Grafana on Minikube
on:
  - push
  - pull_request
env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: 'environments/dev'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          file: docker/Dockerfile_openresty
          push: true
          tags: ghcr.io/katzefudder/openresty:latest
  Wordpress_on_Minikube:
    runs-on: ubuntu-latest
    name: Wordpress on Minikube
    steps:
    - name: Install tfenv
      run: git clone https://github.com/tfutils/tfenv.git ~/.tfenv && sudo rm /usr/local/bin/terraform && sudo ln -s ~/.tfenv/bin/* /usr/local/bin
    - name: Install tgenv
      run: git clone https://github.com/cunymatthieu/tgenv.git ~/.tgenv && sudo ln -s ~/.tgenv/bin/* /usr/local/bin
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: Install required Terraform & Terragrunt versions
      run: cd environments && tfenv install && tgenv install
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: enable ingress
      run: minikube addons enable ingress
    - name: removing validation webhook
      run: kubectl delete  validatingwebhookconfigurations ingress-nginx-admission
    - name: 'Terragrunt Init'
      run: cd $tf_working_dir && terragrunt init
    - name: 'Terragrunt Apply'
      run: cd $tf_working_dir && terragrunt apply --auto-approve --input=false
    - name: show running pods
      run: kubectl get pods -n dev-wordpress
    - name: test output
      run: curl -v --fail --silent -IL $(minikube ip) | grep "HTTP/1.1 200 OK"